import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1754920486672 implements MigrationInterface {
    name = 'InitialSchema1754920486672'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "admins" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "email" character varying(200) NOT NULL, "password" character varying(255) NOT NULL, "refreshToken" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_051db7d37d478a69a7432df1479" UNIQUE ("email"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."analytics_type_enum" AS ENUM('travel_overview', 'travel_members', 'travel_activity', 'travel_engagement', 'travel_growth', 'planet_activity', 'planet_messages', 'planet_engagement', 'planet_performance', 'user_activity', 'user_engagement', 'user_journey', 'system_performance', 'system_usage')`);
        await queryRunner.query(`CREATE TYPE "public"."analytics_period_enum" AS ENUM('hourly', 'daily', 'weekly', 'monthly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "analytics" ("id" SERIAL NOT NULL, "type" "public"."analytics_type_enum" NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" integer NOT NULL, "period" "public"."analytics_period_enum" NOT NULL, "date" date NOT NULL, "metrics" json NOT NULL, "dimensions" json, "comparison" json, "forecast" json, "label" character varying(100), "description" text, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c96dcbf1e4c57ea9e0c3144bff" PRIMARY KEY ("id")); COMMENT ON COLUMN "analytics"."type" IS '분석 데이터 타입'; COMMENT ON COLUMN "analytics"."entityType" IS '대상 엔티티 타입 (travel, planet, user 등)'; COMMENT ON COLUMN "analytics"."entityId" IS '대상 엔티티 ID'; COMMENT ON COLUMN "analytics"."period" IS '집계 주기'; COMMENT ON COLUMN "analytics"."date" IS '집계 날짜'; COMMENT ON COLUMN "analytics"."metrics" IS '집계된 메트릭 데이터 (JSON)'; COMMENT ON COLUMN "analytics"."dimensions" IS '차원별 분석 데이터 (JSON)'; COMMENT ON COLUMN "analytics"."comparison" IS '이전 기간 대비 변화량 (JSON)'; COMMENT ON COLUMN "analytics"."forecast" IS '예측/전망 데이터 (JSON)'; COMMENT ON COLUMN "analytics"."label" IS '분석 데이터 제목/라벨'; COMMENT ON COLUMN "analytics"."description" IS '분석 데이터 설명'; COMMENT ON COLUMN "analytics"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "analytics"."createdAt" IS '분석 데이터 생성 시간'; COMMENT ON COLUMN "analytics"."updatedAt" IS '분석 데이터 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_2de1d3124c07ed32d4c9e0c2a6" ON "analytics" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f60eaca1334fca31ef3c28588" ON "analytics" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed6d4b0e2e5467752cb14a44d" ON "analytics" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f7b67c0ae5e101b71e86a0cf5" ON "analytics" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_19da8ae5e50dce0825eeaf1d1f" ON "analytics" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ddb1767051ba238bb698c3e08" ON "analytics" ("type", "period", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_efb0bbda7c7b63593f3b65db2d" ON "analytics" ("entityType", "entityId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8d9e131a97cc6e9d00979720c" ON "analytics" ("type", "entityType", "entityId", "period") `);
        await queryRunner.query(`CREATE TYPE "public"."users_provider_enum" AS ENUM('google', 'apple')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('online', 'offline', 'away', 'busy')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "socialId" character varying(255) NOT NULL, "provider" "public"."users_provider_enum" NOT NULL, "name" character varying(100) NOT NULL, "email" character varying(200) NOT NULL, "avatar" text, "status" "public"."users_status_enum" NOT NULL DEFAULT 'offline', "isOnline" boolean NOT NULL DEFAULT false, "lastSeenAt" TIMESTAMP, "notificationsEnabled" boolean NOT NULL DEFAULT false, "language" character varying(10) NOT NULL DEFAULT 'ko', "timezone" character varying(50) NOT NULL DEFAULT 'Asia/Seoul', "refreshToken" character varying(255), "refreshTokenExpiresAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "isBanned" boolean NOT NULL DEFAULT false, "banExpiresAt" TIMESTAMP, "loginCount" integer NOT NULL DEFAULT '0', "firstLoginAt" TIMESTAMP, "socialMetadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")); COMMENT ON COLUMN "users"."socialId" IS '소셜 로그인 고유 ID'; COMMENT ON COLUMN "users"."provider" IS '소셜 로그인 제공자 (Google, Apple)'; COMMENT ON COLUMN "users"."name" IS '사용자 이름'; COMMENT ON COLUMN "users"."email" IS '이메일 주소'; COMMENT ON COLUMN "users"."avatar" IS '프로필 이미지 URL'; COMMENT ON COLUMN "users"."status" IS '사용자 온라인 상태'; COMMENT ON COLUMN "users"."isOnline" IS '현재 온라인 여부 (실시간)'; COMMENT ON COLUMN "users"."lastSeenAt" IS '마지막 접속 시간'; COMMENT ON COLUMN "users"."notificationsEnabled" IS '알림 수신 여부'; COMMENT ON COLUMN "users"."language" IS '언어 설정'; COMMENT ON COLUMN "users"."timezone" IS '시간대 설정'; COMMENT ON COLUMN "users"."refreshToken" IS 'Refresh Token'; COMMENT ON COLUMN "users"."refreshTokenExpiresAt" IS 'Refresh Token 만료 시간'; COMMENT ON COLUMN "users"."isActive" IS '계정 활성화 여부'; COMMENT ON COLUMN "users"."isBanned" IS '계정 정지 여부'; COMMENT ON COLUMN "users"."banExpiresAt" IS '정지 해제 시간'; COMMENT ON COLUMN "users"."loginCount" IS '로그인 횟수'; COMMENT ON COLUMN "users"."firstLoginAt" IS '첫 로그인 시간'; COMMENT ON COLUMN "users"."socialMetadata" IS '소셜 로그인 추가 정보 (JSON)'; COMMENT ON COLUMN "users"."createdAt" IS '계정 생성 시간'; COMMENT ON COLUMN "users"."updatedAt" IS '정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_2025eaefc4e1b443c84f6ca9b2" ON "users" ("socialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4305aedaa7aed08419da6a29ec" ON "users" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c75e77b20aed2d8633d83dc767" ON "users" ("isOnline") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0e1a27f5119514e54547f02c8" ON "users" ("lastSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_836026b660a661f0dbdc467bf1" ON "users" ("isBanned") `);
        await queryRunner.query(`CREATE INDEX "IDX_96056fe8ab8748b090b8419ad3" ON "users" ("banExpiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d5efa4db71a540f016110b32d" ON "users" ("isOnline", "lastSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e179ff3144072962c9664df09" ON "users" ("isBanned", "banExpiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe9fad8d1971b7fded468011a2" ON "users" ("provider", "isOnline") `);
        await queryRunner.query(`CREATE INDEX "IDX_b91ab6d821bbe820b09753a151" ON "users" ("status", "isOnline") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df40ea35845296666f010e5d60" ON "users" ("socialId", "provider") `);
        await queryRunner.query(`CREATE TYPE "public"."file_uploads_uploadtype_enum" AS ENUM('single', 'multipart')`);
        await queryRunner.query(`CREATE TYPE "public"."file_uploads_status_enum" AS ENUM('pending', 'uploading', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "file_uploads" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "originalFileName" character varying(255) NOT NULL, "storageKey" character varying(500) NOT NULL, "mimeType" character varying(100) NOT NULL, "fileSize" bigint NOT NULL, "uploadType" "public"."file_uploads_uploadtype_enum" NOT NULL, "status" "public"."file_uploads_status_enum" NOT NULL DEFAULT 'pending', "uploadId" character varying(100), "totalChunks" integer NOT NULL DEFAULT '0', "completedChunks" integer NOT NULL DEFAULT '0', "uploadedBytes" bigint NOT NULL DEFAULT '0', "progress" integer NOT NULL DEFAULT '0', "folder" character varying(50), "publicUrl" text, "metadata" json, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "lastChunkUploadedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_b3ebfc99a8b660f0bc64a052b42" PRIMARY KEY ("id")); COMMENT ON COLUMN "file_uploads"."userId" IS '업로드한 사용자 ID'; COMMENT ON COLUMN "file_uploads"."originalFileName" IS '원본 파일명'; COMMENT ON COLUMN "file_uploads"."storageKey" IS '스토리지 키 (경로)'; COMMENT ON COLUMN "file_uploads"."mimeType" IS '파일 MIME 타입'; COMMENT ON COLUMN "file_uploads"."fileSize" IS '파일 크기 (bytes)'; COMMENT ON COLUMN "file_uploads"."uploadType" IS '업로드 타입'; COMMENT ON COLUMN "file_uploads"."status" IS '업로드 상태'; COMMENT ON COLUMN "file_uploads"."uploadId" IS '업로드 ID (멀티파트)'; COMMENT ON COLUMN "file_uploads"."totalChunks" IS '전체 청크 수'; COMMENT ON COLUMN "file_uploads"."completedChunks" IS '완료된 청크 수'; COMMENT ON COLUMN "file_uploads"."uploadedBytes" IS '업로드된 바이트 수'; COMMENT ON COLUMN "file_uploads"."progress" IS '진행률 (0-100)'; COMMENT ON COLUMN "file_uploads"."folder" IS '업로드 폴더'; COMMENT ON COLUMN "file_uploads"."publicUrl" IS '파일 공개 URL'; COMMENT ON COLUMN "file_uploads"."metadata" IS '추가 메타데이터'; COMMENT ON COLUMN "file_uploads"."errorMessage" IS '실패 사유'; COMMENT ON COLUMN "file_uploads"."retryCount" IS '재시도 횟수'; COMMENT ON COLUMN "file_uploads"."startedAt" IS '업로드 시작 시간'; COMMENT ON COLUMN "file_uploads"."completedAt" IS '업로드 완료 시간'; COMMENT ON COLUMN "file_uploads"."lastChunkUploadedAt" IS '마지막 청크 업로드 시간'; COMMENT ON COLUMN "file_uploads"."createdAt" IS '생성 시간'; COMMENT ON COLUMN "file_uploads"."updatedAt" IS '수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_94ebfb8561e9ec5a73f4825303" ON "file_uploads" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b9c79f1f9c829564bc687f967" ON "file_uploads" ("storageKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_708122a96c2c29befcb55304b2" ON "file_uploads" ("uploadType") `);
        await queryRunner.query(`CREATE INDEX "IDX_5092ff1043be76e3f343af4586" ON "file_uploads" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_20f0c90a9578b335c737f478a0" ON "file_uploads" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8047436ae0058cbc312ce9e13" ON "file_uploads" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_77a304d841bf3286f8a730d319" ON "file_uploads" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."travels_status_enum" AS ENUM('planning', 'active', 'completed', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TYPE "public"."travels_visibility_enum" AS ENUM('public', 'private', 'invite_only')`);
        await queryRunner.query(`CREATE TABLE "travels" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "imageUrl" text, "createdBy" integer NOT NULL, "status" "public"."travels_status_enum" NOT NULL DEFAULT 'planning', "isActive" boolean NOT NULL DEFAULT true, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "expiryDate" TIMESTAMP NOT NULL, "visibility" "public"."travels_visibility_enum" NOT NULL DEFAULT 'invite_only', "inviteCode" character varying(20), "inviteCodeEnabled" boolean NOT NULL DEFAULT true, "maxPlanets" integer NOT NULL DEFAULT '10', "maxGroupMembers" integer NOT NULL DEFAULT '100', "memberCount" integer NOT NULL DEFAULT '0', "planetCount" integer NOT NULL DEFAULT '0', "totalMessages" integer NOT NULL DEFAULT '0', "lastActivityAt" TIMESTAMP, "settings" json, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_428300708b878e464fcbfcccd2f" UNIQUE ("inviteCode"), CONSTRAINT "PK_cc2d44f93ba8f6b268978971e2b" PRIMARY KEY ("id")); COMMENT ON COLUMN "travels"."name" IS '여행 이름'; COMMENT ON COLUMN "travels"."description" IS '여행 설명'; COMMENT ON COLUMN "travels"."imageUrl" IS '여행 이미지 URL'; COMMENT ON COLUMN "travels"."createdBy" IS '여행 생성자 ID'; COMMENT ON COLUMN "travels"."status" IS '여행 상태'; COMMENT ON COLUMN "travels"."isActive" IS '활성 상태'; COMMENT ON COLUMN "travels"."startDate" IS '여행 시작 예정 날짜'; COMMENT ON COLUMN "travels"."endDate" IS '여행 종료 예정 날짜'; COMMENT ON COLUMN "travels"."expiryDate" IS '채팅 만료 날짜 (이후 채팅 불가)'; COMMENT ON COLUMN "travels"."visibility" IS '공개 설정'; COMMENT ON COLUMN "travels"."inviteCode" IS '초대 코드 (공유용)'; COMMENT ON COLUMN "travels"."inviteCodeEnabled" IS '초대 코드 활성화 여부'; COMMENT ON COLUMN "travels"."maxPlanets" IS '최대 Planet 개수'; COMMENT ON COLUMN "travels"."maxGroupMembers" IS '그룹 Planet 최대 멤버 수'; COMMENT ON COLUMN "travels"."memberCount" IS '현재 멤버 수'; COMMENT ON COLUMN "travels"."planetCount" IS '현재 Planet 수'; COMMENT ON COLUMN "travels"."totalMessages" IS '총 메시지 수'; COMMENT ON COLUMN "travels"."lastActivityAt" IS '마지막 활동 시간'; COMMENT ON COLUMN "travels"."settings" IS 'Travel 세부 설정 (JSON)'; COMMENT ON COLUMN "travels"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "travels"."createdAt" IS '여행 생성 시간'; COMMENT ON COLUMN "travels"."updatedAt" IS '여행 정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_aab47f49c5905c4ec321b1e40f" ON "travels" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_d00c3d134d3e58ae1315ad3073" ON "travels" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6749e5c85f0c4c389188bc670d" ON "travels" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_23e6daba79c39cfeabbe392c24" ON "travels" ("expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fe038bd7626c36eee32e4379c" ON "travels" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_428300708b878e464fcbfcccd2" ON "travels" ("inviteCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_db62f526a964878cf88774366e" ON "travels" ("lastActivityAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2133ee47bddbababf8be3b32cf" ON "travels" ("createdBy", "isActive", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b6d1a848b08eb3295654d72b4" ON "travels" ("createdBy", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f6bb380e067912ecc66cdd5f6" ON "travels" ("visibility", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_4aae6d1c93e593cb1f0aab1efa" ON "travels" ("status", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd3938a1923f9c141a64c6ecb6" ON "travels" ("isActive", "expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4fb0a4e891a5be7dd4b3cbb7b" ON "travels" ("status", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."planets_type_enum" AS ENUM('group', 'direct')`);
        await queryRunner.query(`CREATE TYPE "public"."planets_status_enum" AS ENUM('active', 'inactive', 'archived', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "planets" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "imageUrl" text, "type" "public"."planets_type_enum" NOT NULL, "travelId" integer NOT NULL, "createdBy" integer NOT NULL, "status" "public"."planets_status_enum" NOT NULL DEFAULT 'active', "isActive" boolean NOT NULL DEFAULT true, "timeRestriction" json, "memberCount" integer NOT NULL DEFAULT '0', "maxMembers" integer NOT NULL DEFAULT '100', "messageCount" integer NOT NULL DEFAULT '0', "lastMessageAt" TIMESTAMP, "lastMessagePreview" character varying(200), "lastMessageUserId" integer, "settings" json, "partnerId" integer, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d5fbc2513a6d4909fe31938b0fd" PRIMARY KEY ("id")); COMMENT ON COLUMN "planets"."name" IS 'Planet 이름'; COMMENT ON COLUMN "planets"."description" IS 'Planet 설명'; COMMENT ON COLUMN "planets"."imageUrl" IS 'Planet 아이콘 또는 이미지 URL'; COMMENT ON COLUMN "planets"."type" IS 'Planet 타입 (단체/1:1)'; COMMENT ON COLUMN "planets"."travelId" IS '소속 Travel ID'; COMMENT ON COLUMN "planets"."createdBy" IS 'Planet 생성자 ID'; COMMENT ON COLUMN "planets"."status" IS 'Planet 상태'; COMMENT ON COLUMN "planets"."isActive" IS '활성 상태'; COMMENT ON COLUMN "planets"."timeRestriction" IS '시간 제한 설정 (JSON)'; COMMENT ON COLUMN "planets"."memberCount" IS '현재 멤버 수'; COMMENT ON COLUMN "planets"."maxMembers" IS '최대 멤버 수'; COMMENT ON COLUMN "planets"."messageCount" IS '총 메시지 수'; COMMENT ON COLUMN "planets"."lastMessageAt" IS '마지막 메시지 시간'; COMMENT ON COLUMN "planets"."lastMessagePreview" IS '마지막 메시지 내용 (미리보기용)'; COMMENT ON COLUMN "planets"."lastMessageUserId" IS '마지막 메시지 보낸 사용자 ID'; COMMENT ON COLUMN "planets"."settings" IS 'Planet 세부 설정 (JSON)'; COMMENT ON COLUMN "planets"."partnerId" IS '1:1 채팅 상대방 ID (DIRECT 타입 전용)'; COMMENT ON COLUMN "planets"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "planets"."createdAt" IS 'Planet 생성 시간'; COMMENT ON COLUMN "planets"."updatedAt" IS 'Planet 정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_16fe0bd3b41a5966b4255b75f4" ON "planets" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e417f6ed6c57fa9cfdf0f376c0" ON "planets" ("travelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4aa241d18d17e7227088d5bde" ON "planets" ("createdBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d118e0ce2d8b41fb1eb057ab8" ON "planets" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b13da0eaf6dd939079539f2b65" ON "planets" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_24a3e4bf7aabe83d7979796c75" ON "planets" ("memberCount") `);
        await queryRunner.query(`CREATE INDEX "IDX_72cb259a83425cb3683f0577b5" ON "planets" ("messageCount") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a0d637e2260b129070b2f4eec" ON "planets" ("lastMessageAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee8cf285073ffc55c4e1185cd1" ON "planets" ("partnerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc1cac38c163a79396bbe9d859" ON "planets" ("travelId", "isActive", "lastMessageAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_eee212e33743a60f811a333c19" ON "planets" ("isActive", "lastMessageAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6de171d8cbf6c3b97270273142" ON "planets" ("createdBy", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_788648558c18fba1e3806d7b9a" ON "planets" ("type", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_68de525d0258210981bb4f6408" ON "planets" ("travelId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_36d9c08ea0fc09772a29855277" ON "planets" ("travelId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_f019dabaf3859fab20e1da9c8b" ON "planets" ("travelId", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'video', 'file', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('sent', 'delivered', 'read', 'failed', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" SERIAL NOT NULL, "type" "public"."messages_type_enum" NOT NULL, "planetId" integer NOT NULL, "senderId" integer NOT NULL, "content" text, "fileMetadata" json, "systemMetadata" json, "status" "public"."messages_status_enum" NOT NULL DEFAULT 'sent', "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "deletedBy" integer, "isEdited" boolean NOT NULL DEFAULT false, "editedAt" TIMESTAMP, "originalContent" text, "replyToMessageId" integer, "replyCount" integer NOT NULL DEFAULT '0', "readCount" integer NOT NULL DEFAULT '0', "firstReadAt" TIMESTAMP, "reactions" json, "searchableText" text, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id")); COMMENT ON COLUMN "messages"."type" IS '메시지 타입'; COMMENT ON COLUMN "messages"."planetId" IS '소속 Planet ID'; COMMENT ON COLUMN "messages"."senderId" IS '메시지 발신자 ID'; COMMENT ON COLUMN "messages"."content" IS '메시지 내용 (텍스트)'; COMMENT ON COLUMN "messages"."fileMetadata" IS '파일 메타데이터 (JSON)'; COMMENT ON COLUMN "messages"."systemMetadata" IS '시스템 메시지 메타데이터 (JSON)'; COMMENT ON COLUMN "messages"."status" IS '메시지 상태'; COMMENT ON COLUMN "messages"."isDeleted" IS '삭제 여부 (소프트 삭제)'; COMMENT ON COLUMN "messages"."deletedAt" IS '삭제 시간'; COMMENT ON COLUMN "messages"."deletedBy" IS '삭제한 사용자 ID'; COMMENT ON COLUMN "messages"."isEdited" IS '편집 여부'; COMMENT ON COLUMN "messages"."editedAt" IS '마지막 편집 시간'; COMMENT ON COLUMN "messages"."originalContent" IS '편집 전 원본 내용'; COMMENT ON COLUMN "messages"."replyToMessageId" IS '답장 대상 메시지 ID'; COMMENT ON COLUMN "messages"."replyCount" IS '답장 메시지 개수'; COMMENT ON COLUMN "messages"."readCount" IS '읽음 확인한 사용자 수'; COMMENT ON COLUMN "messages"."firstReadAt" IS '첫 읽음 시간'; COMMENT ON COLUMN "messages"."reactions" IS '메시지 반응 정보 (JSON)'; COMMENT ON COLUMN "messages"."searchableText" IS '검색용 텍스트 (인덱싱용)'; COMMENT ON COLUMN "messages"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "messages"."createdAt" IS '메시지 전송 시간'; COMMENT ON COLUMN "messages"."updatedAt" IS '메시지 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_87183e91f31c528f4abc1cdc51" ON "messages" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c525b7857818c79931d5875d88" ON "messages" ("planetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2db9cf2b3ca111742793f6c37c" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_befd307485dbf0559d17e4a4d2" ON "messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f84c237b7406e33771839742c" ON "messages" ("isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_5af59aa83a3b266bb35c0b5573" ON "messages" ("isEdited") `);
        await queryRunner.query(`CREATE INDEX "IDX_0262e5d715a726bdaefe6340e5" ON "messages" ("editedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e18c5bd9344f845152f61f5c5" ON "messages" ("replyToMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_50e74137f3a0ca84a100130f3f" ON "messages" ("searchableText") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ce6acdb0801254590f8a78c08" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_29184560395328217ac21a8ea6" ON "messages" ("senderId", "type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_706eed08cb5e027fe5e9fcb9a0" ON "messages" ("planetId", "isDeleted", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_67588f76828ebebd2bfe971afd" ON "messages" ("planetId", "type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4840fed5ef9baa08c4c314503" ON "messages" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dfe166ccdd53722597a90f6324" ON "messages" ("type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b6f42dcafbc76eb6f4f8bc5c5" ON "messages" ("planetId", "isDeleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b3c4f4471f43b1a17771ae579" ON "messages" ("planetId", "senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3f7cfa28b3ec132c53b48114b" ON "messages" ("planetId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_40dc3de52ed041e48cfb116f2a" ON "messages" ("senderId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_aedeb5ba7b4beb916caf3704fd" ON "messages" ("planetId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('message_received', 'message_mention', 'message_reply', 'message_edited', 'message_deleted', 'travel_invitation', 'travel_join_request', 'travel_member_joined', 'travel_member_left', 'travel_expiry_warning', 'travel_expired', 'travel_updated', 'travel_deleted', 'planet_created', 'planet_invitation', 'planet_member_joined', 'planet_member_left', 'planet_updated', 'planet_deleted', 'user_banned', 'user_unbanned', 'user_role_changed', 'system_announcement', 'system_maintenance', 'system_update')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'read', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(100) NOT NULL, "content" text NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'normal', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "travelId" integer, "planetId" integer, "messageId" integer, "triggeredBy" integer, "channels" json NOT NULL, "deliveryResults" json, "scheduledAt" TIMESTAMP, "expiresAt" TIMESTAMP, "data" json, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id")); COMMENT ON COLUMN "notifications"."userId" IS '알림 받을 사용자 ID'; COMMENT ON COLUMN "notifications"."type" IS '알림 타입'; COMMENT ON COLUMN "notifications"."title" IS '알림 제목'; COMMENT ON COLUMN "notifications"."content" IS '알림 내용'; COMMENT ON COLUMN "notifications"."priority" IS '알림 우선순위'; COMMENT ON COLUMN "notifications"."status" IS '알림 상태'; COMMENT ON COLUMN "notifications"."isRead" IS '읽음 여부'; COMMENT ON COLUMN "notifications"."readAt" IS '읽은 시간'; COMMENT ON COLUMN "notifications"."travelId" IS '관련 Travel ID'; COMMENT ON COLUMN "notifications"."planetId" IS '관련 Planet ID'; COMMENT ON COLUMN "notifications"."messageId" IS '관련 메시지 ID'; COMMENT ON COLUMN "notifications"."triggeredBy" IS '알림 발생시킨 사용자 ID'; COMMENT ON COLUMN "notifications"."channels" IS '전송할 채널 목록'; COMMENT ON COLUMN "notifications"."deliveryResults" IS '채널별 전송 결과'; COMMENT ON COLUMN "notifications"."scheduledAt" IS '예약 전송 시간'; COMMENT ON COLUMN "notifications"."expiresAt" IS '알림 만료 시간'; COMMENT ON COLUMN "notifications"."data" IS '알림 관련 추가 데이터 (JSON)'; COMMENT ON COLUMN "notifications"."metadata" IS '알림 메타데이터 (JSON)'; COMMENT ON COLUMN "notifications"."createdAt" IS '알림 생성 시간'; COMMENT ON COLUMN "notifications"."updatedAt" IS '알림 정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d992705797d7d2d5a3853ad9c" ON "notifications" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ba28344602d583583b9ea1a50" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_357d60c1b7e4a2e9466d6ff356" ON "notifications" ("travelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c92fb969e67cbf7208462ebc0" ON "notifications" ("planetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3bff6ef995abfa317b8ec8699" ON "notifications" ("scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_831a5a06f879fb0bebf8965871" ON "notifications" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d06d6169ad1f3d8f83d63902b" ON "notifications" ("planetId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_3363924e627d40f4b945c3276f" ON "notifications" ("travelId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab221329a9f4c2111690d52f34" ON "notifications" ("status", "scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8cfc4757bd393ac9aec5dde530" ON "notifications" ("userId", "type", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_78207b2dc2b0d717649e89d3fc" ON "notifications" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE TYPE "public"."performance_metrics_type_enum" AS ENUM('api_response_time', 'database_query_time', 'cache_hit_rate', 'file_upload_speed', 'file_download_speed', 'file_processing_time', 'websocket_connection', 'memory_usage', 'cpu_usage', 'disk_usage', 'error_rate', 'concurrent_users')`);
        await queryRunner.query(`CREATE TYPE "public"."performance_metrics_category_enum" AS ENUM('api', 'database', 'cache', 'file_storage', 'websocket', 'system', 'error', 'user')`);
        await queryRunner.query(`CREATE TABLE "performance_metrics" ("id" SERIAL NOT NULL, "type" "public"."performance_metrics_type_enum" NOT NULL, "category" "public"."performance_metrics_category_enum" NOT NULL, "resourceType" character varying(50), "resourceId" bigint, "value" numeric(10,4) NOT NULL, "unit" character varying(20) NOT NULL DEFAULT 'ms', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66237d8c606d64c7bd44a91f74a" PRIMARY KEY ("id")); COMMENT ON COLUMN "performance_metrics"."type" IS '메트릭 타입'; COMMENT ON COLUMN "performance_metrics"."category" IS '메트릭 카테고리'; COMMENT ON COLUMN "performance_metrics"."resourceType" IS '리소스 타입 (travel, planet, message, file)'; COMMENT ON COLUMN "performance_metrics"."resourceId" IS '리소스 ID'; COMMENT ON COLUMN "performance_metrics"."value" IS '메트릭 값'; COMMENT ON COLUMN "performance_metrics"."unit" IS '메트릭 단위 (ms, MB, %, count 등)'; COMMENT ON COLUMN "performance_metrics"."metadata" IS '추가 메타데이터'; COMMENT ON COLUMN "performance_metrics"."createdAt" IS '메트릭 수집 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_2bef716900dbbccbd555e5c12b" ON "performance_metrics" ("resourceType", "resourceId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2125db1843eac07c93e51ffc44" ON "performance_metrics" ("category", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a6d170110f78c019d52a3a219" ON "performance_metrics" ("type", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."performance_alerts_metrictype_enum" AS ENUM('api_response_time', 'database_query_time', 'cache_hit_rate', 'file_upload_speed', 'file_download_speed', 'file_processing_time', 'websocket_connection', 'memory_usage', 'cpu_usage', 'disk_usage', 'error_rate', 'concurrent_users')`);
        await queryRunner.query(`CREATE TABLE "performance_alerts" ("id" SERIAL NOT NULL, "metricType" "public"."performance_alerts_metrictype_enum" NOT NULL, "severity" character varying(20) NOT NULL, "title" character varying(200) NOT NULL, "description" text NOT NULL, "threshold" numeric(10,4) NOT NULL, "currentValue" numeric(10,4) NOT NULL, "resourceType" character varying(50), "resourceId" bigint, "isResolved" boolean NOT NULL DEFAULT false, "resolvedAt" TIMESTAMP, "context" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2c8afd8c56b21d899190efada5" PRIMARY KEY ("id")); COMMENT ON COLUMN "performance_alerts"."metricType" IS '관련 메트릭 타입'; COMMENT ON COLUMN "performance_alerts"."severity" IS '알람 심각도 (low, medium, high, critical)'; COMMENT ON COLUMN "performance_alerts"."title" IS '알람 제목'; COMMENT ON COLUMN "performance_alerts"."description" IS '알람 설명'; COMMENT ON COLUMN "performance_alerts"."threshold" IS '임계값'; COMMENT ON COLUMN "performance_alerts"."currentValue" IS '현재 값'; COMMENT ON COLUMN "performance_alerts"."resourceType" IS '관련 리소스 타입'; COMMENT ON COLUMN "performance_alerts"."resourceId" IS '관련 리소스 ID'; COMMENT ON COLUMN "performance_alerts"."isResolved" IS '해결 여부'; COMMENT ON COLUMN "performance_alerts"."resolvedAt" IS '해결 시간'; COMMENT ON COLUMN "performance_alerts"."context" IS '추가 컨텍스트 정보'; COMMENT ON COLUMN "performance_alerts"."createdAt" IS '알람 생성 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_98beeb207e1899f23889784fa0" ON "performance_alerts" ("severity", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c97dc2425b67aca17c4a4aca94" ON "performance_alerts" ("isResolved", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."planet_users_role_enum" AS ENUM('participant', 'creator', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."planet_users_status_enum" AS ENUM('active', 'left', 'banned', 'invited', 'muted')`);
        await queryRunner.query(`CREATE TABLE "planet_users" ("id" SERIAL NOT NULL, "planetId" integer NOT NULL, "userId" integer NOT NULL, "role" "public"."planet_users_role_enum" NOT NULL DEFAULT 'participant', "status" "public"."planet_users_status_enum" NOT NULL DEFAULT 'active', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastSeenAt" TIMESTAMP, "leftAt" TIMESTAMP, "invitedBy" integer, "invitedAt" TIMESTAMP, "respondedAt" TIMESTAMP, "lastReadMessageId" integer, "lastReadAt" TIMESTAMP, "unreadCount" integer NOT NULL DEFAULT '0', "notificationsEnabled" boolean NOT NULL DEFAULT true, "isMuted" boolean NOT NULL DEFAULT false, "muteUntil" TIMESTAMP, "isBanned" boolean NOT NULL DEFAULT false, "bannedAt" TIMESTAMP, "banExpiresAt" TIMESTAMP, "bannedBy" integer, "banReason" text, "permissions" json, "personalSettings" json, "messageCount" integer NOT NULL DEFAULT '0', "fileCount" integer NOT NULL DEFAULT '0', "firstMessageAt" TIMESTAMP, "lastMessageAt" TIMESTAMP, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7bfe37092ce6937249a233f2f82" UNIQUE ("planetId", "userId"), CONSTRAINT "PK_acf6c79aaef79afacbd248d90d4" PRIMARY KEY ("id")); COMMENT ON COLUMN "planet_users"."planetId" IS 'Planet ID'; COMMENT ON COLUMN "planet_users"."userId" IS '사용자 ID'; COMMENT ON COLUMN "planet_users"."role" IS 'Planet 내 역할'; COMMENT ON COLUMN "planet_users"."status" IS '참여 상태'; COMMENT ON COLUMN "planet_users"."joinedAt" IS '참여 날짜'; COMMENT ON COLUMN "planet_users"."lastSeenAt" IS '마지막 접속 시간'; COMMENT ON COLUMN "planet_users"."leftAt" IS '탈퇴 날짜'; COMMENT ON COLUMN "planet_users"."invitedBy" IS '초대한 사용자 ID'; COMMENT ON COLUMN "planet_users"."invitedAt" IS '초대 날짜'; COMMENT ON COLUMN "planet_users"."respondedAt" IS '초대 응답 날짜'; COMMENT ON COLUMN "planet_users"."lastReadMessageId" IS '마지막 읽은 메시지 ID'; COMMENT ON COLUMN "planet_users"."lastReadAt" IS '마지막 읽음 시간'; COMMENT ON COLUMN "planet_users"."unreadCount" IS '읽지 않은 메시지 수'; COMMENT ON COLUMN "planet_users"."notificationsEnabled" IS '알림 활성화 여부'; COMMENT ON COLUMN "planet_users"."isMuted" IS '음소거 상태'; COMMENT ON COLUMN "planet_users"."muteUntil" IS '음소거 해제 시간'; COMMENT ON COLUMN "planet_users"."isBanned" IS '정지 여부'; COMMENT ON COLUMN "planet_users"."bannedAt" IS '정지 시작 시간'; COMMENT ON COLUMN "planet_users"."banExpiresAt" IS '정지 해제 시간'; COMMENT ON COLUMN "planet_users"."bannedBy" IS '정지 처리한 관리자 ID'; COMMENT ON COLUMN "planet_users"."banReason" IS '정지 사유'; COMMENT ON COLUMN "planet_users"."permissions" IS 'Planet 내 개별 권한 설정 (JSON)'; COMMENT ON COLUMN "planet_users"."personalSettings" IS 'Planet별 개인 설정 (JSON)'; COMMENT ON COLUMN "planet_users"."messageCount" IS 'Planet에서 전송한 메시지 수'; COMMENT ON COLUMN "planet_users"."fileCount" IS '업로드한 파일 수'; COMMENT ON COLUMN "planet_users"."firstMessageAt" IS '첫 메시지 전송 시간'; COMMENT ON COLUMN "planet_users"."lastMessageAt" IS '마지막 메시지 전송 시간'; COMMENT ON COLUMN "planet_users"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "planet_users"."createdAt" IS '레코드 생성 시간'; COMMENT ON COLUMN "planet_users"."updatedAt" IS '레코드 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_d8bd8b9a9d3f9b29642fbcdf7f" ON "planet_users" ("planetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_818d0335cf3edc9c3abdee1972" ON "planet_users" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_33d45514d19073da22af67c3ac" ON "planet_users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fd7cb74394de10f7b106fd603" ON "planet_users" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_607736bbd033835dbc7021fcd5" ON "planet_users" ("joinedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_75f9c367325d72ee720fb6959f" ON "planet_users" ("lastReadMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b695cd6a2251661385019f2ee4" ON "planet_users" ("planetId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."profiles_gender_enum" AS ENUM('male', 'female', 'other', 'prefer_not_to_say')`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "nickname" character varying(50) NOT NULL, "name" character varying(100) NOT NULL, "gender" "public"."profiles_gender_enum", "age" integer, "occupation" character varying(100), "bio" text, "profileImageUrl" character varying(500), "settings" json, CONSTRAINT "UQ_315ecd98bd1a42dcf2ec4e2e985" UNIQUE ("userId"), CONSTRAINT "REL_315ecd98bd1a42dcf2ec4e2e98" UNIQUE ("userId"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id")); COMMENT ON COLUMN "profiles"."userId" IS '사용자 ID'; COMMENT ON COLUMN "profiles"."nickname" IS '닉네임'; COMMENT ON COLUMN "profiles"."name" IS '실제 이름'; COMMENT ON COLUMN "profiles"."gender" IS '성별'; COMMENT ON COLUMN "profiles"."age" IS '나이'; COMMENT ON COLUMN "profiles"."occupation" IS '직업'; COMMENT ON COLUMN "profiles"."bio" IS '자기소개'; COMMENT ON COLUMN "profiles"."profileImageUrl" IS '프로필 이미지 URL'; COMMENT ON COLUMN "profiles"."settings" IS '추가 프로필 설정 (JSON)'`);
        await queryRunner.query(`CREATE INDEX "IDX_315ecd98bd1a42dcf2ec4e2e98" ON "profiles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a53cb2bff1e60b60dc581f86e0" ON "profiles" ("nickname") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e9da7cade0e9edd393329bb32" ON "profiles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c35f68cf9bffba7318d38df06" ON "profiles" ("gender") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0ace4433aa579fd89ca8a9263" ON "profiles" ("age") `);
        await queryRunner.query(`CREATE INDEX "IDX_483f310ad49bb8d80d328ec1cb" ON "profiles" ("occupation") `);
        await queryRunner.query(`CREATE INDEX "IDX_017f608d9e982cd3dac97c24b7" ON "profiles" ("occupation", "age") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ae7bd3626371cc459b2fc5abd" ON "profiles" ("gender", "age") `);
        await queryRunner.query(`CREATE TABLE "message_read_receipts" ("id" SERIAL NOT NULL, "messageId" integer NOT NULL, "userId" integer NOT NULL, "planetId" integer NOT NULL, "isRead" boolean NOT NULL DEFAULT true, "readAt" TIMESTAMP NOT NULL DEFAULT now(), "deviceType" character varying(50), "userAgent" character varying(500), "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_14760574686d908c45d6d01e66b" UNIQUE ("messageId", "userId"), CONSTRAINT "PK_765a476d3a8f61e3cb7e634a12d" PRIMARY KEY ("id")); COMMENT ON COLUMN "message_read_receipts"."messageId" IS '메시지 ID'; COMMENT ON COLUMN "message_read_receipts"."userId" IS '사용자 ID'; COMMENT ON COLUMN "message_read_receipts"."planetId" IS 'Planet ID'; COMMENT ON COLUMN "message_read_receipts"."isRead" IS '읽음 여부'; COMMENT ON COLUMN "message_read_receipts"."readAt" IS '읽은 시간'; COMMENT ON COLUMN "message_read_receipts"."deviceType" IS '읽은 디바이스 타입'; COMMENT ON COLUMN "message_read_receipts"."userAgent" IS 'User Agent'; COMMENT ON COLUMN "message_read_receipts"."metadata" IS '추가 읽음 메타데이터'; COMMENT ON COLUMN "message_read_receipts"."createdAt" IS '읽음 영수증 생성 시간'; COMMENT ON COLUMN "message_read_receipts"."updatedAt" IS '읽음 영수증 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_7b27375e3d32b327050103cf6d" ON "message_read_receipts" ("messageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1623e4199eb5e0d7296a8b7001" ON "message_read_receipts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bff4fa0608d13320f6190e89" ON "message_read_receipts" ("planetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fd7f571013a6ff16989ec2b67" ON "message_read_receipts" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_2424661325554a5f311edba865" ON "message_read_receipts" ("readAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5cf5f31935f02d1a0d826e406" ON "message_read_receipts" ("planetId", "messageId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba0217f42f94cb307275fbaa21" ON "message_read_receipts" ("planetId", "userId", "readAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7617348fe6ebc428baf261a00" ON "message_read_receipts" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a895db011eb67687a96983e2a" ON "message_read_receipts" ("messageId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_35f4639557c709dc5ea16bcd47" ON "message_read_receipts" ("planetId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_25fedd09f1d588d47a17c63627" ON "message_read_receipts" ("planetId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."security_events_type_enum" AS ENUM('login_attempt', 'login_success', 'login_failure', 'permission_denied', 'rate_limit_exceeded', 'suspicious_activity', 'file_scan_threat', 'unauthorized_access', 'data_breach_attempt', 'brute_force_attack', 'malware_detected', 'spam_detected', 'ip_blocked', 'session_hijack', 'privilege_escalation')`);
        await queryRunner.query(`CREATE TYPE "public"."security_events_risklevel_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."security_events_status_enum" AS ENUM('detected', 'investigating', 'resolved', 'false_positive', 'ignored')`);
        await queryRunner.query(`CREATE TABLE "security_events" ("id" SERIAL NOT NULL, "type" "public"."security_events_type_enum" NOT NULL, "riskLevel" "public"."security_events_risklevel_enum" NOT NULL, "status" "public"."security_events_status_enum" NOT NULL DEFAULT 'detected', "title" character varying(200) NOT NULL, "description" text NOT NULL, "userId" bigint, "ipAddress" character varying(45), "userAgent" character varying(500), "requestUrl" character varying(100), "requestMethod" character varying(10), "resourceType" character varying(50), "resourceId" bigint, "fileName" character varying(100), "fileType" character varying(50), "fileSize" bigint, "metadata" jsonb, "detectionSource" character varying(100), "resolvedAt" TIMESTAMP, "resolvedBy" bigint, "resolutionNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fc100d6700780737348df0d3ae" PRIMARY KEY ("id")); COMMENT ON COLUMN "security_events"."type" IS '보안 이벤트 타입'; COMMENT ON COLUMN "security_events"."riskLevel" IS '위험도 수준'; COMMENT ON COLUMN "security_events"."status" IS '이벤트 상태'; COMMENT ON COLUMN "security_events"."title" IS '이벤트 제목'; COMMENT ON COLUMN "security_events"."description" IS '이벤트 설명'; COMMENT ON COLUMN "security_events"."userId" IS '관련 사용자 ID'; COMMENT ON COLUMN "security_events"."ipAddress" IS 'IP 주소'; COMMENT ON COLUMN "security_events"."userAgent" IS 'User Agent'; COMMENT ON COLUMN "security_events"."requestUrl" IS '요청 URL'; COMMENT ON COLUMN "security_events"."requestMethod" IS 'HTTP 메서드'; COMMENT ON COLUMN "security_events"."resourceType" IS '리소스 타입 (travel, planet, message, file)'; COMMENT ON COLUMN "security_events"."resourceId" IS '리소스 ID'; COMMENT ON COLUMN "security_events"."fileName" IS '파일명 (파일 관련 이벤트)'; COMMENT ON COLUMN "security_events"."fileType" IS '파일 타입'; COMMENT ON COLUMN "security_events"."fileSize" IS '파일 크기 (바이트)'; COMMENT ON COLUMN "security_events"."metadata" IS '추가 메타데이터'; COMMENT ON COLUMN "security_events"."detectionSource" IS '탐지 규칙/소스'; COMMENT ON COLUMN "security_events"."resolvedAt" IS '해결 시간'; COMMENT ON COLUMN "security_events"."resolvedBy" IS '해결한 관리자 ID'; COMMENT ON COLUMN "security_events"."resolutionNotes" IS '해결 방법/노트'; COMMENT ON COLUMN "security_events"."createdAt" IS '이벤트 발생 시간'; COMMENT ON COLUMN "security_events"."updatedAt" IS '이벤트 정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_f3e3edb95aee90264572beb037" ON "security_events" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d52eb18cb798b56183a5ba026" ON "security_events" ("ipAddress", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fbca62d08363c92a9d9b018e7" ON "security_events" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f06b2b465fad556113072868c" ON "security_events" ("riskLevel", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f116fc4d9a5d4b71c9ef5fd75" ON "security_events" ("type", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."blocked_ips_risklevel_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "blocked_ips" ("id" SERIAL NOT NULL, "ipAddress" character varying(45) NOT NULL, "reason" character varying(100) NOT NULL, "riskLevel" "public"."blocked_ips_risklevel_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "blockedUntil" TIMESTAMP, "blockedBy" bigint, "blockCount" bigint NOT NULL DEFAULT '1', "lastViolationAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fac0434f296f6ea4c7c9328ac70" UNIQUE ("ipAddress"), CONSTRAINT "PK_e86c3986ac081ad24d5443bb6c5" PRIMARY KEY ("id")); COMMENT ON COLUMN "blocked_ips"."ipAddress" IS 'IP 주소'; COMMENT ON COLUMN "blocked_ips"."reason" IS '차단 사유'; COMMENT ON COLUMN "blocked_ips"."riskLevel" IS '위험도 수준'; COMMENT ON COLUMN "blocked_ips"."isActive" IS '차단 활성 상태'; COMMENT ON COLUMN "blocked_ips"."blockedUntil" IS '차단 해제 시간 (null이면 영구)'; COMMENT ON COLUMN "blocked_ips"."blockedBy" IS '차단한 관리자 ID'; COMMENT ON COLUMN "blocked_ips"."blockCount" IS '차단 횟수'; COMMENT ON COLUMN "blocked_ips"."lastViolationAt" IS '마지막 위반 시간'; COMMENT ON COLUMN "blocked_ips"."metadata" IS '추가 메타데이터'; COMMENT ON COLUMN "blocked_ips"."createdAt" IS '최초 차단 시간'; COMMENT ON COLUMN "blocked_ips"."updatedAt" IS '차단 정보 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_47cc1acf1ebcf1339703ce5ff6" ON "blocked_ips" ("blockedUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_a51f029a276f27bfe2aa5f45eb" ON "blocked_ips" ("ipAddress", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."file_scan_results_threatlevel_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "file_scan_results" ("id" SERIAL NOT NULL, "fileHash" character varying(64) NOT NULL, "fileName" character varying(200) NOT NULL, "mimeType" character varying(100) NOT NULL, "fileSize" bigint NOT NULL, "scanStatus" character varying(20) NOT NULL DEFAULT 'pending', "threatLevel" "public"."file_scan_results_threatlevel_enum", "isMalicious" boolean NOT NULL DEFAULT false, "isSpam" boolean NOT NULL DEFAULT false, "scanResults" json, "uploadedBy" bigint, "uploadIp" character varying(45), "storageKey" character varying(200), "scanStartedAt" TIMESTAMP, "scanCompletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_69eda00f3412cc18e0c29087d53" PRIMARY KEY ("id")); COMMENT ON COLUMN "file_scan_results"."fileHash" IS '파일 해시 (SHA-256)'; COMMENT ON COLUMN "file_scan_results"."fileName" IS '파일명'; COMMENT ON COLUMN "file_scan_results"."mimeType" IS '파일 MIME 타입'; COMMENT ON COLUMN "file_scan_results"."fileSize" IS '파일 크기 (바이트)'; COMMENT ON COLUMN "file_scan_results"."scanStatus" IS '스캔 상태 (pending, scanning, completed, failed)'; COMMENT ON COLUMN "file_scan_results"."threatLevel" IS '위협 수준'; COMMENT ON COLUMN "file_scan_results"."isMalicious" IS '악성 코드 탐지 여부'; COMMENT ON COLUMN "file_scan_results"."isSpam" IS '스팸 탐지 여부'; COMMENT ON COLUMN "file_scan_results"."scanResults" IS '스캔 엔진 결과'; COMMENT ON COLUMN "file_scan_results"."uploadedBy" IS '업로드한 사용자 ID'; COMMENT ON COLUMN "file_scan_results"."uploadIp" IS '업로드 IP 주소'; COMMENT ON COLUMN "file_scan_results"."storageKey" IS '스토리지 키'; COMMENT ON COLUMN "file_scan_results"."scanStartedAt" IS '스캔 시작 시간'; COMMENT ON COLUMN "file_scan_results"."scanCompletedAt" IS '스캔 완료 시간'; COMMENT ON COLUMN "file_scan_results"."createdAt" IS '스캔 요청 시간'; COMMENT ON COLUMN "file_scan_results"."updatedAt" IS '스캔 결과 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d15fe035bac2ad94309fb197" ON "file_scan_results" ("threatLevel", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6d9a00c97d66c1a19002c7f3c" ON "file_scan_results" ("scanStatus", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_756bc06193e427679971a1b753" ON "file_scan_results" ("fileHash") `);
        await queryRunner.query(`CREATE TYPE "public"."streaming_sessions_status_enum" AS ENUM('active', 'paused', 'ended', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."streaming_sessions_devicetype_enum" AS ENUM('mobile', 'tablet', 'desktop', 'tv', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "streaming_sessions" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "sessionId" character varying(100) NOT NULL, "storageKey" character varying(500) NOT NULL, "status" "public"."streaming_sessions_status_enum" NOT NULL DEFAULT 'active', "currentQuality" character varying(20) NOT NULL, "initialQuality" character varying(20) NOT NULL, "deviceType" "public"."streaming_sessions_devicetype_enum" NOT NULL DEFAULT 'unknown', "userAgent" character varying(500), "ipAddress" character varying(45), "bytesTransferred" bigint NOT NULL DEFAULT '0', "qualityChanges" integer NOT NULL DEFAULT '0', "bufferingEvents" integer NOT NULL DEFAULT '0', "totalBufferingTime" integer NOT NULL DEFAULT '0', "playbackTime" integer NOT NULL DEFAULT '0', "estimatedBandwidth" integer, "averageBitrate" double precision NOT NULL DEFAULT '0', "qualityHistory" json, "bufferingHistory" json, "errorLogs" json, "country" character varying(100), "city" character varying(100), "edgeServer" character varying(100), "startedAt" TIMESTAMP, "endedAt" TIMESTAMP, "lastActivityAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "UQ_4aa80510b4575df66c292e89987" UNIQUE ("sessionId"), CONSTRAINT "PK_201536a9e168b9c96d94efd3c52" PRIMARY KEY ("id")); COMMENT ON COLUMN "streaming_sessions"."userId" IS '스트리밍 요청 사용자 ID'; COMMENT ON COLUMN "streaming_sessions"."sessionId" IS '세션 ID'; COMMENT ON COLUMN "streaming_sessions"."storageKey" IS '스트리밍 파일 키'; COMMENT ON COLUMN "streaming_sessions"."status" IS '세션 상태'; COMMENT ON COLUMN "streaming_sessions"."currentQuality" IS '현재 품질 설정'; COMMENT ON COLUMN "streaming_sessions"."initialQuality" IS '초기 품질 설정'; COMMENT ON COLUMN "streaming_sessions"."deviceType" IS '디바이스 타입'; COMMENT ON COLUMN "streaming_sessions"."userAgent" IS 'User Agent'; COMMENT ON COLUMN "streaming_sessions"."ipAddress" IS 'IP 주소'; COMMENT ON COLUMN "streaming_sessions"."bytesTransferred" IS '전송된 바이트 수'; COMMENT ON COLUMN "streaming_sessions"."qualityChanges" IS '품질 변경 횟수'; COMMENT ON COLUMN "streaming_sessions"."bufferingEvents" IS '버퍼링 이벤트 횟수'; COMMENT ON COLUMN "streaming_sessions"."totalBufferingTime" IS '총 버퍼링 시간 (초)'; COMMENT ON COLUMN "streaming_sessions"."playbackTime" IS '재생 시간 (초)'; COMMENT ON COLUMN "streaming_sessions"."estimatedBandwidth" IS '추정 대역폭 (bps)'; COMMENT ON COLUMN "streaming_sessions"."averageBitrate" IS '평균 비트레이트 (bps)'; COMMENT ON COLUMN "streaming_sessions"."qualityHistory" IS '품질 변경 기록'; COMMENT ON COLUMN "streaming_sessions"."bufferingHistory" IS '버퍼링 이벤트 기록'; COMMENT ON COLUMN "streaming_sessions"."errorLogs" IS '에러 로그'; COMMENT ON COLUMN "streaming_sessions"."country" IS '국가'; COMMENT ON COLUMN "streaming_sessions"."city" IS '도시'; COMMENT ON COLUMN "streaming_sessions"."edgeServer" IS 'CDN 엣지 서버'; COMMENT ON COLUMN "streaming_sessions"."startedAt" IS '스트리밍 시작 시간'; COMMENT ON COLUMN "streaming_sessions"."endedAt" IS '스트리밍 종료 시간'; COMMENT ON COLUMN "streaming_sessions"."lastActivityAt" IS '마지막 활동 시간'; COMMENT ON COLUMN "streaming_sessions"."createdAt" IS '생성 시간'; COMMENT ON COLUMN "streaming_sessions"."updatedAt" IS '수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_7da4c89e756ebc2ad0e10cfd1c" ON "streaming_sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4aa80510b4575df66c292e8998" ON "streaming_sessions" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8bcbe287b93ce79b74f1526e0" ON "streaming_sessions" ("storageKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_813574f76cc6f80e34b7be3020" ON "streaming_sessions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c48bc6e2a736a54172e48372f1" ON "streaming_sessions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_bae40d0905f9cfc420cf62c7cc" ON "streaming_sessions" ("storageKey", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c11115c2556c80155645ca709b" ON "streaming_sessions" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ffcb8f8152b459f7545c7ff03" ON "streaming_sessions" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."travel_users_role_enum" AS ENUM('member', 'admin', 'owner')`);
        await queryRunner.query(`CREATE TYPE "public"."travel_users_status_enum" AS ENUM('pending', 'active', 'left', 'banned', 'invited')`);
        await queryRunner.query(`CREATE TABLE "travel_users" ("id" SERIAL NOT NULL, "travelId" integer NOT NULL, "userId" integer NOT NULL, "role" "public"."travel_users_role_enum" NOT NULL DEFAULT 'member', "status" "public"."travel_users_status_enum" NOT NULL DEFAULT 'active', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastSeenAt" TIMESTAMP, "leftAt" TIMESTAMP, "invitedBy" integer, "invitedAt" TIMESTAMP, "respondedAt" TIMESTAMP, "isBanned" boolean NOT NULL DEFAULT false, "bannedAt" TIMESTAMP, "banExpiresAt" TIMESTAMP, "bannedBy" integer, "banReason" text, "permissions" json, "settings" json, "messageCount" integer NOT NULL DEFAULT '0', "createdPlanetCount" integer NOT NULL DEFAULT '0', "inviteCount" integer NOT NULL DEFAULT '0', "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb3fb6e2f9ba7cbfaa55243691d" UNIQUE ("travelId", "userId"), CONSTRAINT "PK_80cadee462ed211f7ec572962a9" PRIMARY KEY ("id")); COMMENT ON COLUMN "travel_users"."travelId" IS 'Travel ID'; COMMENT ON COLUMN "travel_users"."userId" IS '사용자 ID'; COMMENT ON COLUMN "travel_users"."role" IS 'Travel 내 역할'; COMMENT ON COLUMN "travel_users"."status" IS '참여 상태'; COMMENT ON COLUMN "travel_users"."joinedAt" IS '가입 날짜'; COMMENT ON COLUMN "travel_users"."lastSeenAt" IS '마지막 접속 시간'; COMMENT ON COLUMN "travel_users"."leftAt" IS '탈퇴 날짜'; COMMENT ON COLUMN "travel_users"."invitedBy" IS '초대한 사용자 ID'; COMMENT ON COLUMN "travel_users"."invitedAt" IS '초대 날짜'; COMMENT ON COLUMN "travel_users"."respondedAt" IS '초대 응답 날짜'; COMMENT ON COLUMN "travel_users"."isBanned" IS '정지 여부'; COMMENT ON COLUMN "travel_users"."bannedAt" IS '정지 시작 시간'; COMMENT ON COLUMN "travel_users"."banExpiresAt" IS '정지 해제 시간'; COMMENT ON COLUMN "travel_users"."bannedBy" IS '정지 처리한 관리자 ID'; COMMENT ON COLUMN "travel_users"."banReason" IS '정지 사유'; COMMENT ON COLUMN "travel_users"."permissions" IS '개별 권한 설정 (JSON)'; COMMENT ON COLUMN "travel_users"."settings" IS '사용자별 설정 (JSON)'; COMMENT ON COLUMN "travel_users"."messageCount" IS '전송한 메시지 수'; COMMENT ON COLUMN "travel_users"."createdPlanetCount" IS '생성한 Planet 수'; COMMENT ON COLUMN "travel_users"."inviteCount" IS '초대한 멤버 수'; COMMENT ON COLUMN "travel_users"."metadata" IS '추가 메타데이터 (JSON)'; COMMENT ON COLUMN "travel_users"."createdAt" IS '레코드 생성 시간'; COMMENT ON COLUMN "travel_users"."updatedAt" IS '레코드 수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_845f9301a1c4734d013fcc5359" ON "travel_users" ("travelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e444d7fbe7d18cc67c3b4bcf4" ON "travel_users" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_421650c3f46b2c352dc132bff5" ON "travel_users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcb71b8445a2a38d303f8a12d1" ON "travel_users" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b40a22538d14fd661faadbb0b3" ON "travel_users" ("joinedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1e52a4cae3da00380d2665d4b" ON "travel_users" ("lastSeenAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_3fb2c7d8802c2ca54b53020e04" ON "travel_users" ("leftAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e36689e9fa9ee4a76542e12017" ON "travel_users" ("invitedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_c302178e0f3483a9fc535bd21b" ON "travel_users" ("invitedBy", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b7423cc1117c15104daec4346" ON "travel_users" ("userId", "joinedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b6335b63452e29e35db74964b" ON "travel_users" ("travelId", "status", "role") `);
        await queryRunner.query(`CREATE INDEX "IDX_427bbaf4936558eb4a3f63aab7" ON "travel_users" ("status", "joinedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c53692ef08b82fb3ba4555097d" ON "travel_users" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6eed6909a64c018ad1b237890b" ON "travel_users" ("travelId", "role") `);
        await queryRunner.query(`CREATE INDEX "IDX_1b95562111431ed61ed2dd4ff9" ON "travel_users" ("travelId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."video_processing_processingtype_enum" AS ENUM('compression', 'thumbnail', 'metadata', 'preview', 'full_processing')`);
        await queryRunner.query(`CREATE TYPE "public"."video_processing_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."video_processing_qualityprofile_enum" AS ENUM('low', 'medium', 'high', 'ultra')`);
        await queryRunner.query(`CREATE TABLE "video_processing" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "fileUploadId" integer, "processingType" "public"."video_processing_processingtype_enum" NOT NULL, "status" "public"."video_processing_status_enum" NOT NULL DEFAULT 'pending', "qualityProfile" "public"."video_processing_qualityprofile_enum", "inputStorageKey" character varying(500) NOT NULL, "originalFileName" character varying(255) NOT NULL, "inputFileSize" bigint NOT NULL, "inputMimeType" character varying(100) NOT NULL, "outputStorageKeys" text, "outputTotalSize" bigint, "outputUrls" text, "progress" integer NOT NULL DEFAULT '0', "estimatedDurationSeconds" integer, "actualDurationSeconds" integer, "inputMetadata" json, "outputMetadata" json, "thumbnails" json, "errorMessage" text, "processingLogs" json, "retryCount" integer NOT NULL DEFAULT '0', "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer, "file_upload_id" integer, CONSTRAINT "PK_a6fbdbb2e7956d3681ec6c854ab" PRIMARY KEY ("id")); COMMENT ON COLUMN "video_processing"."userId" IS '요청한 사용자 ID'; COMMENT ON COLUMN "video_processing"."fileUploadId" IS '원본 파일 업로드 ID'; COMMENT ON COLUMN "video_processing"."processingType" IS '프로세싱 타입'; COMMENT ON COLUMN "video_processing"."status" IS '프로세싱 상태'; COMMENT ON COLUMN "video_processing"."qualityProfile" IS '품질 프로필'; COMMENT ON COLUMN "video_processing"."inputStorageKey" IS '원본 파일 스토리지 키'; COMMENT ON COLUMN "video_processing"."originalFileName" IS '원본 파일명'; COMMENT ON COLUMN "video_processing"."inputFileSize" IS '원본 파일 크기 (bytes)'; COMMENT ON COLUMN "video_processing"."inputMimeType" IS '원본 MIME 타입'; COMMENT ON COLUMN "video_processing"."outputStorageKeys" IS '처리된 파일 키들 (JSON)'; COMMENT ON COLUMN "video_processing"."outputTotalSize" IS '출력 파일들 총 크기 (bytes)'; COMMENT ON COLUMN "video_processing"."outputUrls" IS '출력 파일 공개 URLs (JSON)'; COMMENT ON COLUMN "video_processing"."progress" IS '진행률 (0-100)'; COMMENT ON COLUMN "video_processing"."estimatedDurationSeconds" IS '예상 소요 시간 (초)'; COMMENT ON COLUMN "video_processing"."actualDurationSeconds" IS '실제 소요 시간 (초)'; COMMENT ON COLUMN "video_processing"."inputMetadata" IS '입력 파일 메타데이터'; COMMENT ON COLUMN "video_processing"."outputMetadata" IS '출력 파일 메타데이터'; COMMENT ON COLUMN "video_processing"."thumbnails" IS '썸네일 정보'; COMMENT ON COLUMN "video_processing"."errorMessage" IS '에러 메시지'; COMMENT ON COLUMN "video_processing"."processingLogs" IS 'FFmpeg 로그'; COMMENT ON COLUMN "video_processing"."retryCount" IS '재시도 횟수'; COMMENT ON COLUMN "video_processing"."startedAt" IS '프로세싱 시작 시간'; COMMENT ON COLUMN "video_processing"."completedAt" IS '프로세싱 완료 시간'; COMMENT ON COLUMN "video_processing"."createdAt" IS '생성 시간'; COMMENT ON COLUMN "video_processing"."updatedAt" IS '수정 시간'`);
        await queryRunner.query(`CREATE INDEX "IDX_6e03225f2852506b1be1060154" ON "video_processing" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_678139a05090095bbdbde74aa7" ON "video_processing" ("processingType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9bbc19cb5b2dc194a8f7cd777" ON "video_processing" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_657d1c24ce108df7724bbde9fa" ON "video_processing" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5075ec013dfa8440475af765a9" ON "video_processing" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5389e29600e818b9dc863b04fa" ON "video_processing" ("userId", "status") `);
        await queryRunner.query(`ALTER TABLE "file_uploads" ADD CONSTRAINT "FK_e98a66989ce33c0f7343bc502dd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travels" ADD CONSTRAINT "FK_aab47f49c5905c4ec321b1e40f5" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planets" ADD CONSTRAINT "FK_e417f6ed6c57fa9cfdf0f376c00" FOREIGN KEY ("travelId") REFERENCES "travels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planets" ADD CONSTRAINT "FK_e4aa241d18d17e7227088d5bde5" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planets" ADD CONSTRAINT "FK_ee8cf285073ffc55c4e1185cd1a" FOREIGN KEY ("partnerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_c525b7857818c79931d5875d88e" FOREIGN KEY ("planetId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_4e18c5bd9344f845152f61f5c53" FOREIGN KEY ("replyToMessageId") REFERENCES "messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_357d60c1b7e4a2e9466d6ff356d" FOREIGN KEY ("travelId") REFERENCES "travels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_0c92fb969e67cbf7208462ebc04" FOREIGN KEY ("planetId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_7dca5807b6d8c844cfc9f93ce08" FOREIGN KEY ("triggeredBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planet_users" ADD CONSTRAINT "FK_d8bd8b9a9d3f9b29642fbcdf7fc" FOREIGN KEY ("planetId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planet_users" ADD CONSTRAINT "FK_818d0335cf3edc9c3abdee1972e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planet_users" ADD CONSTRAINT "FK_5103d0c0e7e3c1ebcc2bbff514b" FOREIGN KEY ("invitedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" ADD CONSTRAINT "FK_7b27375e3d32b327050103cf6df" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" ADD CONSTRAINT "FK_1623e4199eb5e0d7296a8b70014" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" ADD CONSTRAINT "FK_26bff4fa0608d13320f6190e89a" FOREIGN KEY ("planetId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streaming_sessions" ADD CONSTRAINT "FK_b90ce4b647060200090b56b7077" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_users" ADD CONSTRAINT "FK_845f9301a1c4734d013fcc53590" FOREIGN KEY ("travelId") REFERENCES "travels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_users" ADD CONSTRAINT "FK_5e444d7fbe7d18cc67c3b4bcf44" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "travel_users" ADD CONSTRAINT "FK_e36689e9fa9ee4a76542e12017e" FOREIGN KEY ("invitedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_processing" ADD CONSTRAINT "FK_8154aa1e73e0988bc810f0fe132" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_processing" ADD CONSTRAINT "FK_122e16caa78101d02e0f75e0dd9" FOREIGN KEY ("file_upload_id") REFERENCES "file_uploads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE "query-result-cache" ("id" SERIAL NOT NULL, "identifier" character varying, "time" bigint NOT NULL, "duration" integer NOT NULL, "query" text NOT NULL, "result" text NOT NULL, CONSTRAINT "PK_6a98f758d8bfd010e7e10ffd3d3" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "query-result-cache"`);
        await queryRunner.query(`ALTER TABLE "video_processing" DROP CONSTRAINT "FK_122e16caa78101d02e0f75e0dd9"`);
        await queryRunner.query(`ALTER TABLE "video_processing" DROP CONSTRAINT "FK_8154aa1e73e0988bc810f0fe132"`);
        await queryRunner.query(`ALTER TABLE "travel_users" DROP CONSTRAINT "FK_e36689e9fa9ee4a76542e12017e"`);
        await queryRunner.query(`ALTER TABLE "travel_users" DROP CONSTRAINT "FK_5e444d7fbe7d18cc67c3b4bcf44"`);
        await queryRunner.query(`ALTER TABLE "travel_users" DROP CONSTRAINT "FK_845f9301a1c4734d013fcc53590"`);
        await queryRunner.query(`ALTER TABLE "streaming_sessions" DROP CONSTRAINT "FK_b90ce4b647060200090b56b7077"`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" DROP CONSTRAINT "FK_26bff4fa0608d13320f6190e89a"`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" DROP CONSTRAINT "FK_1623e4199eb5e0d7296a8b70014"`);
        await queryRunner.query(`ALTER TABLE "message_read_receipts" DROP CONSTRAINT "FK_7b27375e3d32b327050103cf6df"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_315ecd98bd1a42dcf2ec4e2e985"`);
        await queryRunner.query(`ALTER TABLE "planet_users" DROP CONSTRAINT "FK_5103d0c0e7e3c1ebcc2bbff514b"`);
        await queryRunner.query(`ALTER TABLE "planet_users" DROP CONSTRAINT "FK_818d0335cf3edc9c3abdee1972e"`);
        await queryRunner.query(`ALTER TABLE "planet_users" DROP CONSTRAINT "FK_d8bd8b9a9d3f9b29642fbcdf7fc"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_7dca5807b6d8c844cfc9f93ce08"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_0c92fb969e67cbf7208462ebc04"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_357d60c1b7e4a2e9466d6ff356d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_4e18c5bd9344f845152f61f5c53"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_c525b7857818c79931d5875d88e"`);
        await queryRunner.query(`ALTER TABLE "planets" DROP CONSTRAINT "FK_ee8cf285073ffc55c4e1185cd1a"`);
        await queryRunner.query(`ALTER TABLE "planets" DROP CONSTRAINT "FK_e4aa241d18d17e7227088d5bde5"`);
        await queryRunner.query(`ALTER TABLE "planets" DROP CONSTRAINT "FK_e417f6ed6c57fa9cfdf0f376c00"`);
        await queryRunner.query(`ALTER TABLE "travels" DROP CONSTRAINT "FK_aab47f49c5905c4ec321b1e40f5"`);
        await queryRunner.query(`ALTER TABLE "file_uploads" DROP CONSTRAINT "FK_e98a66989ce33c0f7343bc502dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5389e29600e818b9dc863b04fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5075ec013dfa8440475af765a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_657d1c24ce108df7724bbde9fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9bbc19cb5b2dc194a8f7cd777"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_678139a05090095bbdbde74aa7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e03225f2852506b1be1060154"`);
        await queryRunner.query(`DROP TABLE "video_processing"`);
        await queryRunner.query(`DROP TYPE "public"."video_processing_qualityprofile_enum"`);
        await queryRunner.query(`DROP TYPE "public"."video_processing_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."video_processing_processingtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b95562111431ed61ed2dd4ff9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6eed6909a64c018ad1b237890b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c53692ef08b82fb3ba4555097d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427bbaf4936558eb4a3f63aab7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b6335b63452e29e35db74964b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b7423cc1117c15104daec4346"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c302178e0f3483a9fc535bd21b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e36689e9fa9ee4a76542e12017"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fb2c7d8802c2ca54b53020e04"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1e52a4cae3da00380d2665d4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b40a22538d14fd661faadbb0b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcb71b8445a2a38d303f8a12d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_421650c3f46b2c352dc132bff5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e444d7fbe7d18cc67c3b4bcf4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_845f9301a1c4734d013fcc5359"`);
        await queryRunner.query(`DROP TABLE "travel_users"`);
        await queryRunner.query(`DROP TYPE "public"."travel_users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."travel_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ffcb8f8152b459f7545c7ff03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c11115c2556c80155645ca709b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bae40d0905f9cfc420cf62c7cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c48bc6e2a736a54172e48372f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_813574f76cc6f80e34b7be3020"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8bcbe287b93ce79b74f1526e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4aa80510b4575df66c292e8998"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7da4c89e756ebc2ad0e10cfd1c"`);
        await queryRunner.query(`DROP TABLE "streaming_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."streaming_sessions_devicetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."streaming_sessions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_756bc06193e427679971a1b753"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6d9a00c97d66c1a19002c7f3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5d15fe035bac2ad94309fb197"`);
        await queryRunner.query(`DROP TABLE "file_scan_results"`);
        await queryRunner.query(`DROP TYPE "public"."file_scan_results_threatlevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a51f029a276f27bfe2aa5f45eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47cc1acf1ebcf1339703ce5ff6"`);
        await queryRunner.query(`DROP TABLE "blocked_ips"`);
        await queryRunner.query(`DROP TYPE "public"."blocked_ips_risklevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f116fc4d9a5d4b71c9ef5fd75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f06b2b465fad556113072868c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fbca62d08363c92a9d9b018e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d52eb18cb798b56183a5ba026"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3e3edb95aee90264572beb037"`);
        await queryRunner.query(`DROP TABLE "security_events"`);
        await queryRunner.query(`DROP TYPE "public"."security_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."security_events_risklevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."security_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25fedd09f1d588d47a17c63627"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35f4639557c709dc5ea16bcd47"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a895db011eb67687a96983e2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7617348fe6ebc428baf261a00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba0217f42f94cb307275fbaa21"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5cf5f31935f02d1a0d826e406"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2424661325554a5f311edba865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fd7f571013a6ff16989ec2b67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26bff4fa0608d13320f6190e89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1623e4199eb5e0d7296a8b7001"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b27375e3d32b327050103cf6d"`);
        await queryRunner.query(`DROP TABLE "message_read_receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ae7bd3626371cc459b2fc5abd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017f608d9e982cd3dac97c24b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_483f310ad49bb8d80d328ec1cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0ace4433aa579fd89ca8a9263"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c35f68cf9bffba7318d38df06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e9da7cade0e9edd393329bb32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a53cb2bff1e60b60dc581f86e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_315ecd98bd1a42dcf2ec4e2e98"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TYPE "public"."profiles_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b695cd6a2251661385019f2ee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75f9c367325d72ee720fb6959f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_607736bbd033835dbc7021fcd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fd7cb74394de10f7b106fd603"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33d45514d19073da22af67c3ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_818d0335cf3edc9c3abdee1972"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8bd8b9a9d3f9b29642fbcdf7f"`);
        await queryRunner.query(`DROP TABLE "planet_users"`);
        await queryRunner.query(`DROP TYPE "public"."planet_users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."planet_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c97dc2425b67aca17c4a4aca94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98beeb207e1899f23889784fa0"`);
        await queryRunner.query(`DROP TABLE "performance_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."performance_alerts_metrictype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a6d170110f78c019d52a3a219"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2125db1843eac07c93e51ffc44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bef716900dbbccbd555e5c12b"`);
        await queryRunner.query(`DROP TABLE "performance_metrics"`);
        await queryRunner.query(`DROP TYPE "public"."performance_metrics_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."performance_metrics_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78207b2dc2b0d717649e89d3fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cfc4757bd393ac9aec5dde530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab221329a9f4c2111690d52f34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3363924e627d40f4b945c3276f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d06d6169ad1f3d8f83d63902b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_831a5a06f879fb0bebf8965871"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3bff6ef995abfa317b8ec8699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c92fb969e67cbf7208462ebc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_357d60c1b7e4a2e9466d6ff356"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ba28344602d583583b9ea1a50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d992705797d7d2d5a3853ad9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aedeb5ba7b4beb916caf3704fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40dc3de52ed041e48cfb116f2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3f7cfa28b3ec132c53b48114b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b3c4f4471f43b1a17771ae579"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b6f42dcafbc76eb6f4f8bc5c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfe166ccdd53722597a90f6324"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4840fed5ef9baa08c4c314503"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67588f76828ebebd2bfe971afd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_706eed08cb5e027fe5e9fcb9a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29184560395328217ac21a8ea6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce6acdb0801254590f8a78c08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50e74137f3a0ca84a100130f3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e18c5bd9344f845152f61f5c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0262e5d715a726bdaefe6340e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5af59aa83a3b266bb35c0b5573"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f84c237b7406e33771839742c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_befd307485dbf0559d17e4a4d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2db9cf2b3ca111742793f6c37c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c525b7857818c79931d5875d88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87183e91f31c528f4abc1cdc51"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f019dabaf3859fab20e1da9c8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36d9c08ea0fc09772a29855277"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68de525d0258210981bb4f6408"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_788648558c18fba1e3806d7b9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6de171d8cbf6c3b97270273142"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eee212e33743a60f811a333c19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc1cac38c163a79396bbe9d859"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee8cf285073ffc55c4e1185cd1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a0d637e2260b129070b2f4eec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72cb259a83425cb3683f0577b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24a3e4bf7aabe83d7979796c75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b13da0eaf6dd939079539f2b65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d118e0ce2d8b41fb1eb057ab8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4aa241d18d17e7227088d5bde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e417f6ed6c57fa9cfdf0f376c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16fe0bd3b41a5966b4255b75f4"`);
        await queryRunner.query(`DROP TABLE "planets"`);
        await queryRunner.query(`DROP TYPE "public"."planets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."planets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4fb0a4e891a5be7dd4b3cbb7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd3938a1923f9c141a64c6ecb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4aae6d1c93e593cb1f0aab1efa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f6bb380e067912ecc66cdd5f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b6d1a848b08eb3295654d72b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2133ee47bddbababf8be3b32cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db62f526a964878cf88774366e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_428300708b878e464fcbfcccd2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fe038bd7626c36eee32e4379c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23e6daba79c39cfeabbe392c24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6749e5c85f0c4c389188bc670d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d00c3d134d3e58ae1315ad3073"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aab47f49c5905c4ec321b1e40f"`);
        await queryRunner.query(`DROP TABLE "travels"`);
        await queryRunner.query(`DROP TYPE "public"."travels_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."travels_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77a304d841bf3286f8a730d319"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8047436ae0058cbc312ce9e13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20f0c90a9578b335c737f478a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5092ff1043be76e3f343af4586"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_708122a96c2c29befcb55304b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b9c79f1f9c829564bc687f967"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94ebfb8561e9ec5a73f4825303"`);
        await queryRunner.query(`DROP TABLE "file_uploads"`);
        await queryRunner.query(`DROP TYPE "public"."file_uploads_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."file_uploads_uploadtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df40ea35845296666f010e5d60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b91ab6d821bbe820b09753a151"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe9fad8d1971b7fded468011a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e179ff3144072962c9664df09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d5efa4db71a540f016110b32d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96056fe8ab8748b090b8419ad3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_836026b660a661f0dbdc467bf1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0e1a27f5119514e54547f02c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c75e77b20aed2d8633d83dc767"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4305aedaa7aed08419da6a29ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2025eaefc4e1b443c84f6ca9b2"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8d9e131a97cc6e9d00979720c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efb0bbda7c7b63593f3b65db2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ddb1767051ba238bb698c3e08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19da8ae5e50dce0825eeaf1d1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f7b67c0ae5e101b71e86a0cf5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed6d4b0e2e5467752cb14a44d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f60eaca1334fca31ef3c28588"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2de1d3124c07ed32d4c9e0c2a6"`);
        await queryRunner.query(`DROP TABLE "analytics"`);
        await queryRunner.query(`DROP TYPE "public"."analytics_period_enum"`);
        await queryRunner.query(`DROP TYPE "public"."analytics_type_enum"`);
        await queryRunner.query(`DROP TABLE "admins"`);
    }

}
